# Generated by Django 2.2.7 on 2020-03-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_Item',
            new_name='CartItem',
        ),
    ]
