# Generated by Django 2.2.7 on 2020-03-16 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200315_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Cart'),
            preserve_default=False,
        ),
    ]
