# Generated by Django 2.2.7 on 2020-03-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200315_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
