# Generated by Django 2.2.7 on 2020-03-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
