# Generated by Django 2.2.7 on 2020-03-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_profile'),
        ('api', '0005_auto_20200316_1243'),
    ]

    operations = [
    ]
